apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  selector:
    app: nginx
    tier: frontend
  ports:
  - port: 80          # Service port
    targetPort: 80    # Container port
    nodePort: 30036   # Exposed on node IP
  type: NodePort
