---
# k8s-deployment-labs/03-recreate-strategy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-recreate
  namespace: sre
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.0
        ports:
        - containerPort: 80
